### ISSUE TITLE
running issue

### ISSUE THREAD

**Issue by chiyuzhang94** [JayYip/m3tl#17]
Hi,
I am trying to run the example in "run self defined problem". But I got error on "Train Model" part. I am using python 3.6.3 and bert-multitask-learning 0.2.7. 
```
Adding new problem imdb_cls, problem type: cls
INFO:tensorflow:Saving preprocessing files to tmp/imdb_cls_train_data.pkl
---------------------------------------------------------------------------
_RemoteTraceback                          Traceback (most recent call last)
_RemoteTraceback: 
'''
Traceback (most recent call last):
  File "/home/chiyu94/bert_multitask/lib/python3.6/site-packages/joblib/externals/loky/process_executor.py", line 391, in _process_worker
    call_item = call_queue.get(block=True, timeout=timeout)
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "/home/chiyu94/bert_multitask/lib/python3.6/site-packages/bert_multitask_learning/__init__.py", line 4, in <module>
    from .model_fn import *
  File "/home/chiyu94/bert_multitask/lib/python3.6/site-packages/bert_multitask_learning/model_fn.py", line 5, in <module>
    from .bert import modeling
ModuleNotFoundError: No module named 'bert_multitask_learning.bert'
'''

The above exception was the direct cause of the following exception:

BrokenProcessPool                         Traceback (most recent call last)
<ipython-input-7-3420e0b145e9> in <module>
      4 train_bert_multitask(problem='imdb_cls', num_gpus=0, 
      5                      num_epochs=10, params=params,
----> 6                      problem_type_dict=new_problem_type, processing_fn_dict=new_problem_process_fn_dict)

/lustre03/project/6007993/chiyu94/bert-multitask-learning-master/bert_multitask_learning/run_bert_multitask.py in train_bert_multitask(problem, num_gpus, num_epochs, model_dir, params, problem_type_dict, processing_fn_dict, model)
    106                 problem_name=new_problem, problem_type=problem_type_dict[new_problem], processing_fn=new_problem_processing_fn)
    107     params.assign_problem(problem, gpu=int(num_gpus),
--> 108                           base_dir=base_dir, dir_name=dir_name)
    109     params.to_json()
    110 

/lustre03/project/6007993/chiyu94/bert-multitask-learning-master/bert_multitask_learning/params.py in assign_problem(self, flag_string, gpu, base_dir, dir_name, is_serve)
    191         self.prepare_dir(base_dir, dir_name, self.problem_list)
    192 
--> 193         self.get_data_info(self.problem_list, self.ckpt_dir)
    194 
    195         if not is_serve:

/lustre03/project/6007993/chiyu94/bert-multitask-learning-master/bert_multitask_learning/params.py in get_data_info(self, problem_list, base)
    255 
    256                     self.data_num_dict[problem] = len(
--> 257                         list(self.read_data_fn[problem](self, 'train')))
    258                     self.data_num += self.data_num_dict[problem]
    259                 else:

/lustre03/project/6007993/chiyu94/bert-multitask-learning-master/bert_multitask_learning/create_generators.py in create_single_problem_generator(problem, inputs_list, target_list, label_encoder, params, tokenizer, mode)
    295 
    296             return_dict_list_list = Parallel(num_process)(delayed(partial_fn)(
--> 297                 example_list=example) for example in example_list
    298             )
    299 

~/bert_multitask/lib/python3.6/site-packages/joblib/parallel.py in __call__(self, iterable)
    932 
    933             with self._backend.retrieval_context():
--> 934                 self.retrieve()
    935             # Make sure that we get a last message telling us we are done
    936             elapsed_time = time.time() - self._start_time

~/bert_multitask/lib/python3.6/site-packages/joblib/parallel.py in retrieve(self)
    831             try:
    832                 if getattr(self._backend, 'supports_timeout', False):
--> 833                     self._output.extend(job.get(timeout=self.timeout))
    834                 else:
    835                     self._output.extend(job.get())

~/bert_multitask/lib/python3.6/site-packages/joblib/_parallel_backends.py in wrap_future_result(future, timeout)
    519         AsyncResults.get from multiprocessing."""
    520         try:
--> 521             return future.result(timeout=timeout)
    522         except LokyTimeoutError:
    523             raise TimeoutError()

/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/concurrent/futures/_base.py in result(self, timeout)
    430                 raise CancelledError()
    431             elif self._state == FINISHED:
--> 432                 return self.__get_result()
    433             else:
    434                 raise TimeoutError()

/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/concurrent/futures/_base.py in __get_result(self)
    382     def __get_result(self):
    383         if self._exception:
--> 384             raise self._exception
    385         else:
    386             return self._result

BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable.
```

**Comment by JayYip** [comment]
Hi, this is indeed a bug. Please update to 0.2.8 and let me know if you still experience any issue. Thanks!

**Comment by chiyuzhang94** [comment]
That's fixed. But new issue come up. 

Adding new problem imdb_cls, problem type: cls
INFO:tensorflow:Saving preprocessing files to tmp/imdb_cls_train_data.pkl
---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-8-3420e0b145e9> in <module>
      4 train_bert_multitask(problem='imdb_cls', num_gpus=0, 
      5                      num_epochs=10, params=params,
----> 6                      problem_type_dict=new_problem_type, processing_fn_dict=new_problem_process_fn_dict)

/lustre03/project/6007993/chiyu94/bert-multitask-learning-master/bert_multitask_learning/run_bert_multitask.py in train_bert_multitask(problem, num_gpus, num_epochs, model_dir, params, problem_type_dict, processing_fn_dict, model)
    106                 problem_name=new_problem, problem_type=problem_type_dict[new_problem], processing_fn=new_problem_processing_fn)
    107     params.assign_problem(problem, gpu=int(num_gpus),
--> 108                           base_dir=base_dir, dir_name=dir_name)
    109     params.to_json()
    110 

/lustre03/project/6007993/chiyu94/bert-multitask-learning-master/bert_multitask_learning/params.py in assign_problem(self, flag_string, gpu, base_dir, dir_name, is_serve)
    202                     dup_fac = 1
    203             self.train_steps = int((
--> 204                 self.data_num * self.train_epoch * dup_fac) / (self.batch_size*gpu))
    205             self.num_warmup_steps = int(0.1 * self.train_steps)
    206 

ZeroDivisionError: division by zero

**Comment by JayYip** [comment]
Sorry about the issue. I used the number of GPU to calculate training steps as you saw in the error. And the error is raised since the `num_gpus` is set to 0. 

BTW, not a good idea to train BERT without a GPU. Even training on the small data like imdb takes a lot of computation.

**Comment by JayYip** [comment]
I'll update the code to catch the exception. Thanks!

**Comment by chiyuzhang94** [comment]
Thanks! Yes, I just noticed this point. I allocate a GPU for it.
